<style>
    table {  font-family: arial, sans-serif;  border-collapse: collapse;  width: 100%;  margin-top: 5px;}
    td, th {  border: 1px solid #dddddd;  text-align: left;  padding: 8px;  }
    tr:nth-child(even) { background-color: #dddddd; }
    .post-id{width:2%} .post-name{width:30%}
</style>

<table>
    <tr>
        <th>Id</th>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Email</th>
        <th>Comment</th>
        <th>Date</th>
    </tr>
    <?php foreach ($block->getItems() as $item) : ?>
        <tr>
            <td><?= $validators = $block->escapeHtml($item->getproduct_comments_id()) ?></td>
            <td><?= $validators = $block->escapeHtml($item->getfirst_name()) ?></td>
            <td><?= $validators = $block->escapeHtml($item->getlast_name()) ?></td>
            <td><?= $validators = $block->escapeHtml($item->getEmail()) ?></td>
            <td><?= $validators = $block->escapeHtml($item->getComment()) ?></td>
            <td><?= $validators = $block->escapeHtml($item->getCreatedAt()) ?></td>
        </tr>
    <?php endforeach; ?>
</table>
