<?php
/** @var \Dev\ProductComments\Block\ProductCommentsBlock $block */


//for using anywhere
//$myBlock = \Magento\Framework\App\ObjectManager::getInstance()->get('Dev\ProductComments\Block\CategoriesBlock');

//echo $block->getCurrentProduct()->getId(). '<br />';
//echo $currentProduct->getName() . '<br />';
//echo $currentProduct->getSku() . '<br />';
//echo $currentProduct->getFinalPrice() . '<br />';
//echo $currentProduct->getProductUrl() . '<br />';
//print_r ($currentProduct->getCategoryIds()) . '<br />';

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$objDate = $objectManager->create('Magento\Framework\Stdlib\DateTime\DateTime');
$comment_date =$objDate->gmtDate();

?>
<form data-mage-init='{"validation":{}}'  action="<?php echo $block->getFormAction() ?>" method="post" class="review-form" id="product-comments">
    <fieldset class="fieldset review-fieldset" data-hasrequired="* Rquired Fields" >
        <legend class="legend review-legend">
            <strong>Product Comments</strong>
        </legend>
        <br>

        <?php foreach($block->getItems() as $item): ?>

            <span><?php echo $item->getComment_date(); ?></span>
            <span style="padding-left: 100px"><b><?php echo $item->getfirst_name().'&nbsp;&nbsp;'.$item->getlast_name(); ?></b></span>
            <div style="background-color: #F5F5F5; margin:10px; padding-left: 10px; padding-right: 10px; padding-top: 0px; padding-bottom: 10px;"><?php echo $item->getComment(); ?></div>
        <?php endforeach; ?>

        <br><br>
        <div class="field required">
            <label for="first_name_field" class="label">
                <span>First Name</span>
            </label>
            <div class="control">
                <input type="text" name="first_name" id="first_name_field" class="input-text"
                       data-validate="{required:true}">
            </div>
        </div>
        <div class="field required">
            <label for="last_name_field" class="label">
                <span>Last Name</span>
            </label>
            <div class="control">
                <input type="text" name="last_name" id="last_name_field" class="input-text"
                       data-validate="{required:true}">
            </div>
        </div>
        <div class="field required">
            <label for="email_field" class="label">
                <span>Email</span>
            </label>
            <div class="control">
                <input type="text" name="email" id="email_field" class="input-text"
                       data-validate="{required:true, 'validate-email':true}" >
            </div>
        </div>
        <div class="field required">
            <label for="comment_field" class="label">
                <span>Comment</span>
            </label>
            <div class="control">
                <textarea name="comment" id="comment_field" cols="5" rows="3"
                          data-validate="{required:true}" ></textarea>
            </div>
        </div>
    </fieldset>
    <div class="actions-toolbar review-form-actions">
        <div class="primary cations-primary">
            <input type="hidden" name="entity_id" id="entity_id_field" value="<?php echo $block->getCurrentProduct()->getId(); ?>">
            <input type="hidden" name="comment_date" id="comment_date_field" value="<?php echo $comment_date; ?>">
            <button type="submit" class="action submit primary">
                <span>Submit Comment</span>
            </button>
        </div>
    </div>
</form>