<?php
$viewModel = $block->getViewModel();
?>
<table>
    <tr>
        <th>Id</th>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Email</th>
        <th>Comment</th>
        <th>Date</th>
    </tr>
    <?php foreach ($viewModel->getItems() as $item) : ?>
        <tr>
            <td><?= $validators = $block->escapeHtml($item->getproduct_comments_id()) ?></td>
            <td><?= $validators = $block->escapeHtml($item->getfirst_name()) ?></td>
            <td><?= $validators = $block->escapeHtml($item->getlast_name()) ?></td>
            <td><?= $validators = $block->escapeHtml($item->getEmail()) ?></td>
            <td><?= $validators = $block->escapeHtml($item->getComment()) ?></td>
            <td><?= $validators = $block->escapeHtml($item->getCreatedAt()) ?></td>
        </tr>
    <?php endforeach; ?>
</table>
